# Generated by Django 5.1.6 on 2025-02-25 07:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_rename_types_filetypes_name_remove_uploads_file_type_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filetypes',
            name='user',
            field=models.ForeignKey(default='empty', on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploads',
            name='category',
            field=models.ForeignKey(default='empty', on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='App1.filetypes'),
        ),
    ]
