# Generated by Django 5.1.6 on 2025-02-25 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0003_alter_filetypes_user_alter_uploads_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetypes',
            old_name='name',
            new_name='types',
        ),
        migrations.RemoveField(
            model_name='filetypes',
            name='user',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='category',
        ),
        migrations.AddField(
            model_name='uploads',
            name='file_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App1.filetypes'),
            preserve_default=False,
        ),
    ]
