# Generated by Django 5.1.6 on 2025-02-25 08:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0004_rename_name_filetypes_types_remove_filetypes_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetypes',
            old_name='types',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='uploads',
            name='file_type',
        ),
        migrations.AddField(
            model_name='filetypes',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uploads',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='App1.filetypes'),
            preserve_default=False,
        ),
    ]
