# Generated by Django 5.1.6 on 2025-02-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0005_rename_types_filetypes_name_remove_uploads_file_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file_path',
            field=models.FileField(max_length=2048, upload_to=''),
        ),
    ]
