# Generated by Django 5.1.6 on 2025-02-25 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0006_alter_uploads_file_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploads',
            name='file_path',
            field=models.CharField(max_length=2048),
        ),
    ]
