# Generated by Django 5.1.6 on 2025-02-26 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0009_remove_folders_user_folders_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetypes',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
