# Generated by Django 5.1.6 on 2025-02-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0010_filetypes_last_modified'),
    ]

    operations = [
        migrations.RenameField(
            model_name='filetypes',
            old_name='last_modified',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='folders',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
