# Generated by Django 5.1.6 on 2025-03-02 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0011_rename_last_modified_filetypes_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='uploads',
            options={'ordering': ['-upload_time']},
        ),
    ]
